# Generated by Django 4.0.4 on 2022-04-16 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=30, unique=True)),
                ('content', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='PasteAnalytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('paste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='paste.paste')),
            ],
        ),
    ]
