# Generated by Django 4.0.4 on 2022-04-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paste',
            name='url',
        ),
        migrations.AddField(
            model_name='paste',
            name='key',
            field=models.CharField(default='', max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pasteanalytic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
